//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHuntOnline.DAL.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> JobID { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ExpectedSalary { get; set; }
        public string Description { get; set; }
        public string CandidateID { get; set; }
        public Nullable<System.Guid> DocumentID { get; set; }
        public Nullable<bool> IsViewed { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
    
        public virtual ApplicationStatu ApplicationStatu { get; set; }
        public virtual Job Job { get; set; }
    }
}
