//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHuntOnline.DAL.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public string UserId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> Location { get; set; }
        public string Description { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
